### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by maccelerated** [leecade/koa-webpack-middleware#1]
Fixed by adding `require('babel-polyfill')` to the top of the dev server. Is it possible to add the runtime to the release version so this isn't necessary for people who don't transpile their server code?

**Comment by chbdetta** [comment]
+1

**Comment by hgenru** [comment]
+1

**Comment by jackhutu** [comment]
+1

**Comment by balkhaev** [comment]
+1

**Comment by concubicycle** [comment]
+1

**Comment by bramblex** [comment]
+1

**Comment by shellscape** [comment]
👍

**Comment by christensson** [comment]
+1

**Comment by zaaack** [comment]
+1

**Comment by oct16** [comment]
+1

**Comment by SeuHkx** [comment]
+1

**Comment by andyhu** [comment]
+1

**Comment by yeluoqiuzhi** [comment]
+1

**Comment by yeluoqiuzhi** [comment]
+1, typescript 2.1

**Comment by Mirodil** [comment]
+1

**Comment by yeluoqiuzhi** [comment]
So this module doesn't work on node 7, which has native support for async function

**Comment by andyhu** [comment]
I switched to `koa-webpack` finally, it's been more actively maintained.

**Comment by yi-ge** [comment]
add regenerator-runtime,require("regenerator-runtime/runtime");

**Comment by dreamstu** [comment]
+1

**Comment by leecade** [comment]
thanks @yi-ge fixed #36
