### ISSUE TITLE
Add feature to use fileSystem

### ISSUE THREAD

**Issue by dxcqcv** [leecade/koa-webpack-middleware#42]
I want to use fileSystem like

    const htmlBuffer = devMiddleware.fileSystem.readFileSync(`${config.output.path}/index.html`)

for now, I get a error like

    TypeError: Cannot read property 'readFileSync' of undefined

I know that devMiddleware from koa-webpack-middleware is a wrapper function of webpack-dev-middleware, has no fileSystem property.

So could you can add this feature ? thanks.

**Comment by gaoqiankun** [comment]
@dxcqcv I got this problem too
@leecade I add this util (and other utils from webpackDevMiddleware) to middleware instance, can you merge the pull request and publish to npm?
