### ISSUE TITLE
1.0.4 is broken in NPM registry

### ISSUE THREAD

**Issue by tnunes** [leecade/koa-webpack-middleware#43]
Latest v1.0.4 published to NPM is broken and is breaking dependent projects.

The published package is missing the `lib/` folder, where the main entry point is declared (`lib/index.js`).

This is causing failures when importing/requiring the module.

Could you please publish a fixed version?

**Comment by xjchenhao** [comment]
sos!

**Comment by leecade** [comment]
sorry, fixed through v1.0.5
