### ISSUE TITLE
Upgrade webpack-dev-middleware to latest version to support webpack 3

### ISSUE THREAD

**Issue by pathikmehta** [leecade/koa-webpack-middleware#51]
Right now it is using webpack-dev-middleware@1.10.2.
webpack-dev-middleware@1.11.0 is available which has the webpack 3 support. 
So need to update the webpack-dev-middleware to support webpack 3 peer dependency in koa-webpack-middleware.

**Comment by xymeng2017** [comment]
up up up

**Comment by leecade** [comment]
fix via 937a03da41e116b2227fd386287d81a5cb102489
